name: docker-on-push

on:
  push:
    branches:
      - 'master'

env:
  IMAGE: schemers/sagittarius

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/sagittarius:0
        id: docker_build_0
        uses: docker/build-push-action@v2
        with:
          push: true
          context: 0/
          tags: |
            ${{ env.IMAGE }}:0
            ${{ env.IMAGE }}:0-bullseye-slim
            ${{ env.IMAGE }}:latest
      -
        name: Build and push schemers/sagittarius:head
        id: docker_build_head
        uses: docker/build-push-action@v2
        with:
          push: true
          context: head/
          tags: |
            ${{ env.IMAGE }}:head
            ${{ env.IMAGE }}:head-bullseye-slim
